### ISSUE TITLE
Are there any sites where this is in use?

### ISSUE THREAD

**Issue by Jieiku** [glosa/glosa-admin#1]
Are there any sites where this is in use?

**Comment by tanrax** [comment]
You just need to startup an instance of Glosa server, and logging in with https://glosa.github.io/glosa-admin/.

**Comment by Jieiku** [comment]
I was mostly trying to get an idea of the size of the js and css that I will need to embed in my blog pages.

The link you shared shows a 12kb app.js and a 186kb chunk-vendors.js, as well as a 45kb main.css

Is this roughly the size of the embed files?

Thanks very much for the reply.

(Also I am now realizing I opened this in the glosa-admin tracker, when what I was really after is the glosa client/embed)

My site is zola so I probably should have opened this here: https://github.com/glosa/glosa-static-integration

I just found this : https://programadorwebvalencia.com/como-usar-kebab-case-camel-case-pascal-case-o-snake-case/

and it appears the comments.js is only 5kb !!! that is awesome! is that the only necessary include?

**Comment by tanrax** [comment]
Hello!
It's OK, you can share your question wherever you need to.
To answer your question, the static example takes up a lot of space because it's built on top of Vue-cli. It was a quick implementation that I built to serve as a base, but implementing it takes very little effort. On my blog, as you have been able to find out, it is quite optimised. Although it was never my goal, but to simplify. To implement it Glosa server is to use its endpoints with JavaScript. If you find the example too heavy, you can always build your own :)
Best regards
